apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: ''
spec:
  containers:
    - args:
      - infinity
      command:
      - sleep
      image: centos:7
      imagePullPolicy: IfNotPresent
      name: tester

