
apiVersion: k8s.jijiechen.com/v1alpha1
kind: CSharpApp
metadata:
  name: hello-console
  namespace: default
spec:
  code: |
    Console.WriteLine("Hello world from CSharp App");
    Thread.Sleep(Timeout.Infinite);
  replicas: 2

