apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: csharpapps.k8s.jijiechen.com
spec:
  group: k8s.jijiechen.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "An application running csharp source"
          properties:
            spec:
              type: object
              required:
              - code
              properties:
                code:
                  type: string
                replicas:
                  type: integer
                  format: int32
                service:
                  type: object
                  description: "Service properties when the application provides network services"
                  properties:
                    port:
                      type: integer
                      format: int32
                    type:
                      enum:
                      - LoadBalancer
                      - ClusterIP
                      - NodePort
                      type: string
                  required:
                  - port
                  
  scope: Namespaced
  names:
    plural: csharpapps
    singular: csharpapp
    kind: CSharpApp
    shortNames:
      - csa
